import type { Metadata } from "next";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { Button } from "@/components/ui/Button";

export const metadata: Metadata = {
  title: "Sample Analysis | Second Opinion AI",
  description: "See a sample clinical reasoning brief generated by Second Opinion AI.",
};

export default function SamplePage() {
  return (
    <main className="flex flex-col items-center w-full">
      {/* 1. Hero */}
      <Section className="pt-40 pb-20 md:pt-56 md:pb-40 bg-[#fafafa]">
        <Container className="max-w-3xl">
          <h1 className="text-5xl md:text-7xl font-medium tracking-tighter text-[#1a1a1a] mb-10 leading-[1.0]">
            What a structured <br /> second opinion should look like.
          </h1>
          <p className="text-xl md:text-3xl text-[#444444] font-light leading-relaxed mb-16">
            A fictional case showing how findings, reasoning, and next steps are organized.
          </p>
          <div className="flex flex-col sm:flex-row gap-8">
            <Button href="/start" variant="primary" className="px-12 py-5 text-xl">Start your case</Button>
            <Button href="/" variant="secondary" className="px-10 py-5 text-lg">Back to homepage</Button>
          </div>
        </Container>
      </Section>

      {/* 2. Disclaimer */}
      <Section className="py-16 border-y border-neutral-200">
        <Container className="max-w-3xl">
          <p className="text-[11px] uppercase tracking-[0.4em] text-[#737373] font-bold mb-6">Demonstration only</p>
          <p className="text-xl text-[#666666] leading-relaxed italic font-serif max-w-2xl">
            This case is fictional and intended for demonstration purposes. It does not provide medical advice, diagnosis, or treatment.
          </p>
        </Container>
      </Section>

      {/* 3. Case Snapshot */}
      <Section className="py-24 md:py-48">
        <Container className="max-w-3xl">
          <h3 className="text-[11px] font-bold uppercase tracking-[0.4em] text-[#2c3e34] mb-16">Case snapshot</h3>
          <p className="text-2xl md:text-4xl text-[#1a1a1a] font-light leading-[1.4] tracking-tight">
            48-year-old female presenting with persistent fatigue, joint pain, and an intermittent rash over an 8-month duration. Previous clinical evaluation focused on stress and physical overuse, but symptoms have persisted despite management.
          </p>
        </Container>
      </Section>

      {/* 4. Timeline */}
      <Section className="py-24 md:py-48 bg-[#fafafa]">
        <Container className="max-w-3xl">
          <h3 className="text-[11px] font-bold uppercase tracking-[0.4em] text-[#2c3e34] mb-20">Timeline</h3>
          <div className="space-y-12 md:space-y-16 border-l border-neutral-200 pl-10 md:pl-16">
            {[
              { time: "Month 1–2", event: "Fatigue and diffuse joint pain begin." },
              { time: "Month 3", event: "Intermittent rash appears on extremities." },
              { time: "Month 5", event: "Initial evaluation attributes symptoms to stress; rest advised." },
              { time: "Month 8", event: "Symptoms persist despite rest and initial management." }
            ].map((item, i) => (
              <div key={i} className="relative">
                <div className="absolute -left-[45px] md:-left-[71px] top-3 w-2.5 h-2.5 rounded-full bg-[#2c3e34]" />
                <p className="text-sm font-bold text-[#737373] uppercase tracking-widest mb-4">{item.time}</p>
                <p className="text-2xl md:text-3xl text-[#1a1a1a] leading-relaxed font-light">{item.event}</p>
              </div>
            ))}
          </div>
        </Container>
      </Section>

      {/* 5. What was reviewed */}
      <Section className="py-24 md:py-48">
        <Container className="max-w-3xl">
          <h3 className="text-[11px] font-bold uppercase tracking-[0.4em] text-[#2c3e34] mb-12">Analysis parameters</h3>
          <p className="text-xl md:text-2xl text-[#444444] font-light leading-relaxed">
            Reviewed materials include complete blood count (CBC) trends, metabolic panels, physician clinical notes, longitudinal symptom history, immunological markers, and available imaging summaries.
          </p>
        </Container>
      </Section>

      {/* 6. Hypotheses */}
      <Section className="py-24 md:py-48 bg-[#fafafa]">
        <Container className="max-w-3xl">
          <h3 className="text-[11px] font-bold uppercase tracking-[0.4em] text-[#2c3e34] mb-20">Analysis of possibilities</h3>
          <div className="space-y-24">
            {[
              { label: "Most consistent with", title: "Autoimmune inflammatory process", desc: "Symptoms involve multiple systems and persist over time, which does not align with a single mechanical or short-term explanation." },
              { label: "Warrants clarification", title: "Chronic inflammatory condition", desc: "The duration and symptom pattern, combined with prior incomplete follow-up, make this a primary area for investigation." },
              { label: "Less consistent with", title: "Isolated endocrine driver", desc: "While fatigue overlaps with endocrine patterns, the broader clinical presentation suggests this may not be the primary driver." }
            ].map((item, i) => (
              <div key={i} className="space-y-6">
                <span className="text-sm font-semibold text-[#737373] uppercase tracking-widest">{item.label}</span>
                <h4 className="text-3xl md:text-5xl font-medium text-[#1a1a1a] tracking-tight">{item.title}</h4>
                <p className="text-xl md:text-2xl text-[#444444] leading-relaxed font-light">{item.desc}</p>
              </div>
            ))}
          </div>
        </Container>
      </Section>

      {/* 7. Why this stands out (ANCHOR) */}
      <Section className="py-24 md:py-48">
        <Container className="max-w-3xl">
          <h3 className="text-[11px] font-bold uppercase tracking-[0.4em] text-[#2c3e34] mb-20">Clinical reasoning summary</h3>
          <ul className="space-y-12">
            {[
              "Symptoms span more than one body system.",
              "The timeline does not fit a short-term stress response.",
              "Prior explanations do not account for the full clinical pattern.",
              "Follow-up appears incomplete relative to symptom persistence."
            ].map((item, i) => (
              <li key={i} className="text-2xl md:text-4xl font-medium text-[#1a1a1a] leading-[1.05] tracking-tighter flex items-start gap-8">
                <span className="text-[#2c3e34] shrink-0 mt-2">•</span>
                {item}
              </li>
            ))}
          </ul>
        </Container>
      </Section>

      {/* 8. What may have been overlooked */}
      <Section className="py-24 md:py-48 bg-[#fafafa]">
        <Container className="max-w-3xl">
          <h3 className="text-[11px] font-bold uppercase tracking-[0.4em] text-[#2c3e34] mb-20">What may need clarification</h3>
          <div className="space-y-20">
            {[
              { title: "Symptom progression", text: "The gradual evolution of symptoms suggests a dynamic process rather than a static state of exhaustion." },
              { title: "Inflammatory pattern", text: "Correlation of findings across multiple visits indicates a systemic rather than localized issue." },
              { title: "Escalation timeline", text: "The persistence of symptoms suggests the need for specialist escalation that has not yet occurred." }
            ].map((item, i) => (
              <div key={i} className="space-y-6">
                <h4 className="text-lg md:text-xl font-bold text-[#1a1a1a] uppercase tracking-[0.2em]">{item.title}</h4>
                <p className="text-2xl md:text-3xl text-[#444444] leading-relaxed font-light">{item.text}</p>
              </div>
            ))}
          </div>
        </Container>
      </Section>

      {/* 9. Questions to bring to your doctor */}
      <Section className="py-24 md:py-48">
        <Container className="max-w-3xl">
          <h3 className="text-[11px] font-bold uppercase tracking-[0.4em] text-[#2c3e34] mb-12">Questions worth clarifying with your physician</h3>
          <div className="space-y-10">
            {[
              "Which findings argue for inflammatory or autoimmune follow-up?",
              "Should prior lab work be repeated or expanded to include specific markers?",
              "Does this clinical pattern justify a rheumatology referral?",
              "Which explanation best fits the full symptom timeline?"
            ].map((item, i) => (
              <div key={i} className="p-10 border border-neutral-200 rounded-3xl bg-[#fafafa]/50 hover:border-[#2c3e34]/30 transition-colors">
                <p className="text-2xl md:text-3xl text-[#1a1a1a] leading-relaxed font-light font-serif italic">
                  &quot;{item}&quot;
                </p>
              </div>
            ))}
          </div>
        </Container>
      </Section>

      {/* 10. Suggested next steps */}
      <Section className="py-24 md:py-48 bg-[#fafafa]">
        <Container className="max-w-3xl">
          <h3 className="text-[11px] font-bold uppercase tracking-[0.4em] text-[#2c3e34] mb-16">Suggested next steps</h3>
          <ul className="space-y-8">
            {[
              "Review trends across prior lab results rather than isolated snapshots.",
              "Reassess unresolved systemic symptoms against existing clinical guidelines.",
              "Consider targeted specialist follow-up based on persistent multisystem patterns.",
              "Compare prior conclusions against the full medical record."
            ].map((item, i) => (
              <li key={i} className="text-xl md:text-2xl text-[#444444] leading-relaxed font-light flex gap-6">
                <span className="text-[#2c3e34] shrink-0">•</span>
                {item}
              </li>
            ))}
          </ul>
        </Container>
      </Section>

      {/* 11. How to read this */}
      <Section className="py-24 md:py-48 border-t border-neutral-200">
        <Container className="max-w-3xl">
          <h3 className="text-[11px] font-bold uppercase tracking-[0.4em] text-[#737373] mb-10">Clinical interpretation</h3>
          <p className="text-xl text-[#666666] leading-relaxed font-light">
            This review clarifies what is most relevant, identifies potential omissions, and structures questions for your next medical consultation. It does not replace clinical judgment or provide a diagnosis.
          </p>
        </Container>
      </Section>

      {/* 12. Final CTA */}
      <Section className="py-24 md:py-48 bg-[#1a1a1a] text-white overflow-hidden relative">
        <div className="absolute top-[-10%] right-[-10%] w-[60%] h-[80%] bg-[#2c3e34] rounded-full blur-[180px] opacity-20 pointer-events-none" />
        <Container className="max-w-4xl text-center relative z-10">
          <h2 className="text-3xl md:text-6xl font-medium tracking-tighter mb-10 md:mb-16 leading-[0.95]">
            Bring clarity <br /> to your own case.
          </h2>
          <p className="text-lg md:text-4xl text-[#a3a3a3] font-light mb-12 md:mb-20 leading-relaxed px-2">
            Upload your records, notes, and symptoms for a structured clinical analysis.
          </p>
          <Button href="/start" variant="none" className="bg-white text-[#1a1a1a] px-12 py-5 md:px-20 md:py-8 text-xl md:text-3xl font-bold rounded-full shadow-[0_0_80px_rgba(255,255,255,0.1)] hover:shadow-[0_20px_80px_rgba(44,62,52,0.4)]">
            Begin Case Analysis
          </Button>
        </Container>
      </Section>
    </main>
  );
}
